# apps/hostinger/docker-compose.vps.yml
# Define los servicios para la configuración hostinger
# Gestionado por el generador @mi-org/vps
services:
  nginx:
    image: nginx:stable-alpine
    container_name: hostinger-nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d:ro
      - ./html:/usr/share/nginx/html:ro
      - /var/www/letsencrypt/challenges:/var/www/letsencrypt/challenges-in-container:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - webproxy

networks:
  webproxy:
    driver: bridge
    name: webproxy
