FROM node:22-alpine

WORKDIR /app

# Instalar git para compatibilidad
RUN apk add --no-cache git

# Para debugging:
ENV NODE_OPTIONS="--inspect=0.0.0.0:9229"

CMD ["npx", "nx", "serve", "miproyecto-scraper-worker"]
