services:
  nginx:
    image: nginx:stable-alpine
    container_name: jupiter-nginx-proxy
    restart: always
    ports:
      - '443:443' # Solo probar 443
    volumes:
      # Montar el DIRECTORIO con el config mínimo en conf.d
      - ./nginx-conf:/etc/nginx/conf.d:ro # <-- Volver a montar el directorio
      # Montar volumen de certs como LECTURA/ESCRITURA para este test
      - certbot-etc:/etc/letsencrypt # <-- Sin :ro TEMPORALMENTE
      # Quitar otros montajes si los quitaste antes
      # - ./nginx-ssl:/etc/nginx/ssl:ro
      # - nginx-logs:/var/log/nginx
    security_opt: # Mantener si crees que AppArmor puede ser factor
      - 'apparmor=unconfined'

  certbot:
    image: certbot/certbot:latest
    container_name: jupiter-certbot
    volumes:
      - certbot-www:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
    entrypoint: 'sleep infinity' # No necesita hacer nada en este test

# Define los volúmenes nombrados para persistir datos importantes
volumes:
  certbot-etc: # Guarda certificados y cuenta de Let's Encrypt
  certbot-www: # Usado para los archivos de desafío HTTP-01
  # nginx-logs:  # Guarda logs de Nginx
