services:
  nginx:
    image: nginx:stable-alpine
    container_name: jupiter-nginx-proxy
    restart: always
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d:ro
      - certbot-etc:/etc/letsencrypt:ro # Mantenemos .ro por seguridad
      - ./nginx-ssl:/etc/nginx/ssl:ro
      - nginx-logs:/var/log/nginx
    networks: # Opcional: Definir una red si es necesario
      - default
    security_opt:
      - 'apparmor=unconfined'

  certbot:
    image: certbot/dns-cloudflare:latest
    container_name: jupiter-certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot # Aunque usemos DNS, lo mantenemos por si acaso
      - /home/deploy/secrets/cloudflare.ini:/etc/letsencrypt/cloudflare.ini:ro
    # entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 1; done'"
    networks:
      - default

volumes:
  certbot-etc: {}
  certbot-www: {}
  nginx-logs: {}

networks:
  default:
    name: jupiter_vps_network
