services:
  nginx:
    image: nginx:stable-alpine
    container_name: jupiter-nginx-proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      # Monta configs generadas (ej. webapp.conf) - Solo lectura
      - ./nginx-conf:/etc/nginx/conf.d:ro
      # Monta volumen para desafíos ACME de Certbot - Solo lectura para Nginx
      - certbot-www:/var/www/certbot:ro
      # Monta volumen para certificados Let's Encrypt - Solo lectura para Nginx
      - certbot-etc:/etc/letsencrypt
      # Monta volumen para logs de Nginx
      - nginx-logs:/var/log/nginx
    # Ya no necesita la red 'app-network'

  # Nuevo servicio para Certbot
  certbot:
    image: certbot/certbot:latest
    container_name: jupiter-certbot
    volumes:
      # Volumen compartido para desafíos ACME - Escritura para Certbot
      - certbot-www:/var/www/certbot
      # Volumen compartido para certificados/configs - Escritura para Certbot
      - certbot-etc:/etc/letsencrypt
    # Comando que se ejecuta al iniciar y luego cada 12h para intentar renovar.
    # Usa el método webroot, que requiere que Nginx sirva los desafíos desde certbot-www.
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet; sleep 12h & wait $${!}; done;'"
    # Nota: La obtención inicial del certificado se hará por separado.

# Define los volúmenes nombrados para persistir datos importantes
volumes:
  certbot-etc: # Guarda certificados y cuenta de Let's Encrypt
  certbot-www: # Usado para los archivos de desafío HTTP-01
  nginx-logs: # Guarda logs de Nginx
