services:
  # Nginx - Reverse Proxy
  nginx:
    image: nginx:stable-alpine # Usar imagen oficial y ligera
    container_name: jupiter-nginx-proxy # Nombre descriptivo
    restart: always
    ports:
      # Expone el puerto 80 del host al 80 del contenedor (para HTTP inicial)
      - '80:80'
      # Expone el puerto 443 (lo descomentaremos cuando configuremos HTTPS)
      # - "443:443"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      # - ./nginx-ssl:/etc/nginx/ssl
      - ./nginx-logs:/var/log/nginx
    extra_hosts:
      # Mapea host.docker.internal a la IP especial del gateway del host de Docker
      - 'host.docker.internal:host-gateway'

# Define los volúmenes que usaremos (si descomentas los mounts de arriba)
volumes:
  # nginx-ssl: # Para certificados
  nginx-logs: # Para logs
