services:
  nginx:
    image: nginx:stable-alpine
    container_name: jupiter-nginx-proxy
    restart: always
    ports:
      # Solo probar 443 por ahora
      - '443:443'
    volumes:
      # Montar el archivo MÍNIMO directamente como nginx.conf principal
      - ./nginx-conf/minimal-ssl.conf:/etc/nginx/nginx.conf:ro
      # Montar volumen de certs como LECTURA/ESCRITURA para este test
      - certbot-etc:/etc/letsencrypt # <-- Sin :ro TEMPORALMENTE
      # Quitar otros montajes de Nginx por ahora si quieres simplificar más
      # - ./nginx-ssl:/etc/nginx/ssl:ro
      # - nginx-logs:/var/log/nginx
    security_opt: # Mantener si crees que AppArmor puede seguir siendo factor
      - 'apparmor=unconfined'

  certbot:
    image: certbot/certbot:latest
    container_name: jupiter-certbot
    volumes:
      - certbot-www:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
    entrypoint: 'sleep infinity' # No necesita hacer nada en este test

# Define los volúmenes nombrados para persistir datos importantes
volumes:
  certbot-etc: # Guarda certificados y cuenta de Let's Encrypt
  certbot-www: # Usado para los archivos de desafío HTTP-01
  # nginx-logs:  # Guarda logs de Nginx
