version: '3.8'

# Docker Compose para arquitectura híbrida (algunos servicios en cloud)
services:
  # Nginx - Proxy inverso y balanceador de carga
  nginx:
    image: nginx:alpine
    container_name: jupiter-nginx
    # Configuración pendiente
    # ...

  # PgBouncer - Conexión a PostgreSQL externo
  pgbouncer:
    image: edoburu/pgbouncer:1.16.0
    container_name: jupiter-pgbouncer
    # Configuración para conectar a PostgreSQL externo
    # ...

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: jupiter-prometheus
    # Configuración pendiente
    # ...

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: jupiter-grafana
    # Configuración pendiente
    # ...
# Networks y Volumes pendientes
