name: Deploy VPS Infrastructure Stack (Manual)

on:
  # Permite la ejecución manual desde la pestaña Actions
  workflow_dispatch:
    inputs:
      infra_name:
        description: 'Select the Infrastructure project name (e.g., hostinger)'
        required: true
        type: choice
        options:
          - hostinger
          # - otro-VPS
        default: 'hostinger' # Opcional: pon el más común por defecto
      target_deploy_path:
         description: 'Absolute path on VPS to deploy infra files'
         required: true
         default: '/home/deploy/infra' # Asume /home/deploy/infra

jobs:
  deploy-infra:
    name: Deploy Infrastructure to VPS
    runs-on: ubuntu-latest

    env:
      TARGET_DEPLOY_PATH: /home/deploy/infra

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Environment Variables from Input
        id: vars # Damos un id para referenciar outputs si fuera necesario
        run: |
          INFRA_NAME="${{ github.event.inputs.infra_name }}"
          # Convertir infra_name a mayúsculas para los nombres de secretos
          INFRA_NAME_UPPER=$(echo "$INFRA_NAME" | tr '[:lower:]' '[:upper:]')

          # Construir las variables dinámicas y exportarlas para pasos posteriores
          echo "INFRA_CONFIG_PATH=infra/${INFRA_NAME}" >> $GITHUB_ENV
          echo "TARGET_HOST_SECRET=VPS_${INFRA_NAME_UPPER}_HOST" >> $GITHUB_ENV
          echo "TARGET_USER_SECRET=VPS_${INFRA_NAME_UPPER}_USER" >> $GITHUB_ENV
          echo "TARGET_KEY_SECRET=VPS_${INFRA_NAME_UPPER}_KEY" >> $GITHUB_ENV

          echo "Derived Variables:"
          echo "INFRA_CONFIG_PATH: infra/${INFRA_NAME}"
          echo "TARGET_HOST_SECRET: VPS_${INFRA_NAME_UPPER}_HOST"
          echo "TARGET_USER_SECRET: VPS_${INFRA_NAME_UPPER}_USER"
          echo "TARGET_KEY_SECRET: VPS_${INFRA_NAME_UPPER}_KEY"
          echo "TARGET_DEPLOY_PATH: ${{ env.TARGET_DEPLOY_PATH }}"

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          # Acceder al secreto usando el nombre dinámico guardado en la variable de entorno
          ssh-private-key: ${{ secrets[env.TARGET_KEY_SECRET] }}

      - name: Add VPS Host to Known Hosts
        run: |
          # Acceder al secreto usando el nombre dinámico
          VPS_HOST="${{ secrets[env.TARGET_HOST_SECRET] }}"
          if [ -z "$VPS_HOST" ]; then echo "Error: Host secret for ${env.TARGET_HOST_SECRET} missing." >&2; exit 1; fi
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H "$VPS_HOST" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          echo "Added $VPS_HOST to known_hosts"

      - name: Install rsync (on runner)
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Sync Infrastructure Files via Rsync
        run: |
          # Acceder a secretos y variables de entorno
          VPS_HOST="${{ secrets[env.TARGET_HOST_SECRET] }}"
          VPS_USER="${{ secrets[env.TARGET_USER_SECRET] || 'deploy' }}" # Puedes hardcodear 'deploy' si siempre es el mismo
          SOURCE_DIR="./${{ env.INFRA_CONFIG_PATH }}/" # Usar la variable de entorno
          TARGET_DIR="${{ env.TARGET_DEPLOY_PATH }}/"   # Usar la variable de entorno (o la ruta fija si no es env var)

          if [ ! -d "$SOURCE_DIR" ]; then echo "Error: Source directory ${SOURCE_DIR} not found in repo." >&2; exit 1; fi

          echo "Syncing ${SOURCE_DIR} to ${VPS_USER}@${VPS_HOST}:${TARGET_DIR}"
          # Asegúrate de que la exclusión de .htpasswd está aquí si la necesitas
          rsync -avz --delete \
            --exclude='.env' \
            --exclude='.gitignore' \
            --exclude='traefik-auth/' \
            "${SOURCE_DIR}" \
            "${VPS_USER}@${VPS_HOST}:${TARGET_DIR}" \
            || { echo "Rsync failed!"; exit 1; }
          echo "Infrastructure files synced successfully to ${TARGET_DIR}"

      - name: Deploy Infrastructure Stack via Docker Compose on VPS
        if: success()
        run: |
          # Acceder a secretos y variables de entorno
          VPS_HOST="${{ secrets[env.TARGET_HOST_SECRET] }}"
          VPS_USER="${{ secrets[env.TARGET_USER_SECRET] || 'deploy' }}"
          INFRA_DIR="${{ env.TARGET_DEPLOY_PATH }}" # Usar la variable de entorno

          echo "Executing docker compose up on ${VPS_USER}@${VPS_HOST} in ${INFRA_DIR}"
          # El script remoto no necesita cambios ya que usa INFRA_DIR y asume que .env y docker-compose están allí
          ssh "${VPS_USER}@${VPS_HOST}" bash -e << EOF
            # --- INICIO SCRIPT REMOTO ---
            echo "[Remote] Changing directory to ${INFRA_DIR}"
            cd "${INFRA_DIR}" || { echo "[Remote] Failed to cd to ${INFRA_DIR}"; exit 1; }

            if [ ! -f "docker-compose-infra.yml" ]; then
              echo "[Remote] ERROR: docker-compose-infra.yml not found in ${INFRA_DIR}" >&2
              exit 1
            fi

            # Verificar .env
            if [ ! -f ".env" ] && [ -f ".env.template" ]; then
              echo "[Remote] ERROR: '.env' file not found, but '.env.template' exists." >&2
              echo "[Remote] Please create '.env' from the template on the server (${INFRA_DIR}/.env)" >&2
              echo "[Remote] and add the required secrets (e.g., DNS provider API keys/tokens needed by Traefik)." >&2
              exit 1 # Fallar si .env falta
            fi

            echo "[Remote] Running docker compose pull..."
            docker compose -f docker-compose-infra.yml pull

            echo "[Remote] Running docker compose up -d..."
            docker compose -f docker-compose-infra.yml up -d --remove-orphans
            COMPOSE_UP_EXIT_CODE=$?

            if [ $COMPOSE_UP_EXIT_CODE -eq 0 ]; then
              echo "[Remote] Docker Compose up command executed successfully (exit code 0)."
              sleep 5
              echo "[Remote] Current container status:"
              docker compose -f docker-compose-infra.yml ps
              exit 0
            else
              echo "[Remote] ERROR: Docker Compose up failed with exit code $COMPOSE_UP_EXIT_CODE." >&2
              echo "[Remote] Attempting to get recent logs..."
              docker compose -f docker-compose-infra.yml logs --tail 30 || echo "[Remote] Failed to get logs."
              exit $COMPOSE_UP_EXIT_CODE
            fi
            # --- FIN SCRIPT REMOTO ---
          EOF
          SSH_EXIT_CODE=$?
          if [ $SSH_EXIT_CODE -ne 0 ]; then
            echo "ERROR: Remote deployment script failed with exit code $SSH_EXIT_CODE!"
            exit $SSH_EXIT_CODE
          fi
          echo "Infrastructure stack deployed/updated successfully via remote script."
