name: CI Build Test - Jupiter App Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_push_app_server:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push jupiter-app-server image
        run: |
          IMAGE_TAG="sha-$(git rev-parse --short HEAD)"
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/jupiter-platform/jupiter-app-server"
          echo "Building and pushing image: $IMAGE_NAME:$IMAGE_TAG"
          docker buildx build --push \
            --tag $IMAGE_NAME:$IMAGE_TAG \
            --file apps/jupiter/app-server/Dockerfile \
            --cache-from=type=gha \
            --cache-to=type=gha,mode=max \
            . # Contexto es la raíz del repo

      - name: Image Built and Pushed
        run: echo "Image ghcr.io/${{ github.repository_owner }}/jupiter-platform/jupiter-app-server:sha-$(git rev-parse --short HEAD) pushed successfully."
